### ISSUE TITLE
Ricerca e Amministrazione contenuti

### ISSUE THREAD

**Issue by lrusnac** [InformaticaSaraLei/ProgettoSito#18]
Salve, si fa una ricerca generale sul sito oppure dobbiamo crearci una ricerca solo per la nostra parte (raccolta esperienze).

C'è un'area per il controllo e amministrazione dei contenuti del sito? Cioè la pagina che inserirà le esperienze sul db dobbiamo integrarla su una cosa più grande oppure una pagina solo per noi?

**Comment by Tpierluigi** [comment]
Chiuso in quanto non sembra sia stato implementato nulla di tutto ciò. se avete necessità, riapritelo pure.
