### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by president1991** [InformaticaSaraLei/ProgettoSito#36]
Ciao, il mio gruppo deve gestire il forum e per fare i test del caso ci siamo appoggiati sul mio sito.
Attualmente il forum è visibile qui: http://ingsw.federicobruni.it
quando bisognerà passare il tutto nel server "definitivo" darò gli accessi ftp al gruppo di integrazione pagine e poi passare le tabelle a quello database.
A parte i fini di consegna non vedo altre motivazioni per caricarlo qui. 
In caso contrario ditemi come preferite.

Saluti
Federico

**Comment by Tpierluigi** [comment]
la chiudo in quanto penso già risolta
