### ISSUE TITLE
Consegna gioco

### ISSUE THREAD

**Issue by RubensCaroti** [InformaticaSaraLei/ProgettoSito#41]
Ciao,

Abbiamo caricato la versione quasi definitiva del gioco. Visti i tempi tecnici per il Db attualmente visualizza dei testi inseriti in degli oggetti che simulano la tabella del Db, sarà nostra cura valutare se effettuare o meno le variazioni.

Fateci sapere se dobbiamo variare qualcosa. 
Resto a disposizione

Rubens

**Comment by Tpierluigi** [comment]
chiudo la issue in quanto il processo di migrazione del gioco sul sito è ormai completato. riapritela pure se ci sono altre cose da sistemare..
