### ISSUE TITLE
Pagine di administrazione

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#57]
Chi ha bisogno di una pagina di admin lo scriva qui

**Comment by klleshi** [comment]
Abbiamo effettuato gli ultimi aggiornamenti su server test01. 
Alcune osservazioni:
Quando “admin” si loga con successo deve essere indirizzato su un pagina che deve contenere tutti i link per effettuare il suo lavoro (aggiungere, modificare …)

La pagina di “cultura” non si ricarica bene e presenta ancora dei problemi come qualche settimana fa.

**Comment by fundor333** [comment]
@klleshi Se elencate i problemi di cultura cerco di sistemarli

**Comment by klleshi** [comment]
- Ci mette un eternità a ricaricarsi
- Blocca per fino il browser
- Non carica le icone dei social

Ha fatto questo problema dopo un aggiornamento di ieri.
Ribadisco: solo la pagina "cultura" rinominata "testimonianze".
Non credo che sia un problema dei miei browser, tutta via provatelo 
anche voi (sul server test01) e fateci sapere.

Il 18/01/2015 21:13, Matteo ha scritto:

**Comment by fundor333** [comment]
Per le icone dei social le ho appena messe a posto.
Il tempo di ricarica è lo stesso della fotogallery per quanto mi riguarda

**Comment by Tpierluigi** [comment]
ciao a tutti,

verificate di aprire le sessioni sui moduli di cui avete richiesto l'amministrazione, ANCHE sulle pagine frontend.

sto ricontrollando il modulo eventi e continuo a riscontrare questo errore. dato che l'amministrazione originariamente non era prevista in questa forma, adesso le pagine che hanno bisogno dell'accesso alla $_SESSION devono aprire la sessione *prima di qualsiasi altra operazione*

Pierluigi Tonegato [Integrazione@controllo]

**Comment by Tpierluigi** [comment]
Sempre nella sezione amministrativa eventi, non c'è maniera di eliminare/annullare eventi inseriti..
Si può aggiungere la funzionalità?

Pierluigi

**Comment by Tpierluigi** [comment]
Un'altra cosa: 
come già anticipato da @klleshi manca una dashboard iniziale dopo la fase di autenticazione: Dato che non ci sono parti da programmare, ma è solo layout grafico, direi di far fare il lavoro al gruppo di struttura e grafica 

Pierluigi Tonegato @InformaticaSaraLei/integrazioneecontrollo

**Comment by Tpierluigi** [comment]
inoltre nella dashboard, oltre a quelle già presenti, vanno le voci per aggiungere/rimuovere utenti dalla newsletter..

**Comment by Tpierluigi** [comment]
@fundor333 siete riusciti a farci qualcosa?

**Comment by fundor333** [comment]
È stata strutturata la dashboard. Tuttu quelli che hanno fatto una pagina di admin per favore inseriscano il link in uno dei tag a liberi presenti nella dashboard

**Comment by klleshi** [comment]
Il server test01 è funzionante ed aggiornato

Il 08/02/2015 18:11, Matteo ha scritto:

**Comment by Tpierluigi** [comment]
Ciao,
Abbiamo necessità di inserire i link sui tag liberi della pagina dashboard.php. successivamente bisognerà o integrare tale pagina in profile.php, oppure farla apparire subito dopo il login. 
@andreafrison 
@lzuffellato 
@lfavaro 
@micheleminighin 
@simonix93 

@InformaticaSaraLei/integrazioneecontrollo
