### ISSUE TITLE
Supporto DB

### ISSUE THREAD

**Issue by TBuc** [InformaticaSaraLei/ProgettoSito#62]
A seguito della riunione del 23 Dicembre, so che alcuni team necessitano di interfacciarsi con noi (Team sviluppo database) per perfezionare il loro lavoro. Finora non ho ricevuto richieste in tal senso.

**Prego quindi chiunque figuri tale necessità di voler usare questo issue per promuovere la propria richiesta.**

Antonio
TL, Team Sviluppo Database

**Comment by Tpierluigi** [comment]
proporrei di chiudere questo issue, @TBuc penso che ormai siate stati già contattati (spero..)

Pierluigi

**Comment by TBuc** [comment]
Pierluigi, negativo. E ho chiesto appositamente di essere contattati qui.
Il 08/feb/2015 16:11 "Tpierluigi" <notifications@github.com> ha scritto:

**Comment by fundor333** [comment]
Per dei test ho eseguito i file sql per la gestione del DB e ho notato che le foto sono quelle non visibili indicate nella issiue #65

**Comment by simonix93** [comment]
il file "SQL - 06 Caricamento dati finali Media.sql" si può anche cancellare poichè i link delle foto non sono più validi. Inoltre ora carichiamo tutto tramite form.

**Comment by TBuc** [comment]
@simonix93 OK, visto che non serve più, ho rimosso il file SQL che avevo predisposto per il caricamento dei vostri dati (file: SQL 06).

**Comment by TBuc** [comment]
@NicolaFrx 
Riporto qui le tue domande. Cito:
`per quanto riguarda il database`
`-le opportunità culturali inserite quali sarebbero?`
`-è possibile concatenare "nuova opportunità di lavoro" con la provincia per piacere?`
`-si può inserire il link relativo all'offerta?`

allora, ti rispondo:
- Attualmente non c'è nessuna opportunità culturali inserita. All'epoca, abbiamo creato una serie di tabelle dietro richiesta dei vari team: ora, alcune di queste tabelle sono ancora vuote (non contengono dati). Sto chiedendo quali di queste tabelle non utilizzate sia possibile rimuovere.
- Non ho capito: mi stai chiedendo se è possibile collegare il campo `offertelavoro`.`AZIENDA_PROVINCIA` ad una tabella che contenga l'elenco delle province?
- Esiste già il campo apposito `offertelavoro`.`FONTE_LINK`

**Comment by NicolaFrx** [comment]
<ul>
<li>Per quanto riguarda le opportunità culturali te l'ho chiesto proprio in vista di una cancellazione dato il mancato utilizzo, a questo punto nel feed comparirebbero esclusivamente le offerte di lavoro e non so quanto sarebbe contestuale alla funzionalità del sito.. 
A questo punto, ti chiedo se risulta essere troppo difficoltoso magari aggiungere all'unione (nella creazione della view) i nuovi interventi del forum oppure i nuovi eventi?</li>

<li>No no, mi son spiegato male, basterebbe aggiungere il campo offertelavoro.AZIENDA_PROVINCIA all'attributo news, modificandolo in "Nuova offerta di lavoro - Zona ".. o magari addirittura in 'Nuova offerta per ',ol.TITOLO_LAVORO,' - ', ol.AZIENDA_PROVINCIA</li>


<li>Quel campo rimanda all'offerta nel sito in cui viene proposta ed è esterno, servirebbe il link generato dalla nuova offerta; la mia richiesta nasce dal fatto che non viene assegnato un link ad ogni articolo dell'rss, il quale indirizza all'index</li>
</ul>

**Comment by Tpierluigi** [comment]
a proposito di opportunità culturali: se faccio una ricerca della stringa "opportunitaculturali" dentro il progetto non trovo niente.. e penso che a questo punto quella roba sia solo da cancellare..

**Comment by Tpierluigi** [comment]
ah.. a proposito di link: ho validato il file rss generato con feedvalidator, e manca anche il tag <guid> (che di solito è uguale al link..)

**Comment by TBuc** [comment]
@NicolaFrx OK, allora da quello che ho capito:
- Ho cancellato le tabelle `opportunitaculturalicarriera` ed `opportunitaculturalipersone`
- Ho aggiunto un campo `OFFERTA_LINK_SITO_PARIOPP` di tipo VARCHAR(200) alla tabella `offertelavoro`. In questo campo andrà inserito un link all'offerta presso il ns. sito.
- Ho rimosso le opportunità culturali dalla vista RSS.
- Ho aggiunto gli eventi alla vista RSS.

Non ho capito invece cosa intendi con:
"basterebbe aggiungere il campo offertelavoro.AZIENDA_PROVINCIA all'attributo news, modificandolo in "Nuova offerta di lavoro - Zona ".. o magari addirittura in 'Nuova offerta per ',ol.TITOLO_LAVORO,' - ', ol.AZIENDA_PROVINCIA"
cosa sarebbe questo "attributo news"? E non ho capito cosa intendi dopo...

P.S. mi dispiace ma ho visto solo oggi questo post. Ripeto: notifiche di GitHub che funzionano come vogliono. Non avrei mai voluto gestire queste cose all'ultimo.

**Comment by NicolaFrx** [comment]
Ottimo grazie! 

Se provi a installare l'rss forse capisci meglio la mi richiesta: si tratterebbe di differenziare i vari "articoli" offerti dal feed già dal titolo, altrimenti la visualizzazione rischia di essere troppo omogenea e non si riescono a distinguere i vari link ai quali punterá..
Sarebbe da trovare un modo per distinguere anche gli eventi, spero tu abbia capito, scusa l'ora ma sono al lavoro

**Comment by NicolaFrx** [comment]
Ah, si tratta di modificare la vista.. 


Comunque visto che ci sono gli eventi servirebbe un campo link anche per gli eventi!

**Comment by NicolaFrx** [comment]
@TBuc

**Comment by Tpierluigi** [comment]
se prendete il feed e lo sottoscrivete, si vedono tutti gli articoli elencati con "nuova offerta di lavoro" oppure "nuovo evento". Se si cliccano non si va alla pagina relativa all'articolo, ma alla home del sito informaticasaralei.. qusto perchè la view è da sistemare: serve un qualcosa di più descrittivo da mettere nel campo "news" e un ulteriore campo che recuperi il link all'offerta di lavoro hostata su sito esterno (il campo offertelavoro.FONTE_LINK, per capirci..)

**Comment by Tpierluigi** [comment]
ok. per far prima ci ho messo io le mani. verificate se ci sono problemi di sorta.
la limitazione della soluzione proposta è che il sito deve essere in root del webserver...
il commit è questo qui: @8c0d7231c6abb011bc60fa30e341894f90db27d4
pierluigi

**Comment by TBuc** [comment]
@NicolaFrx ora mi è chiaro.
@Tpierluigi visto, ottimo lavoro. Ti ringrazio.

Ho visto che hai usato il campo `offertelavoro`.`FONTE_LINK`, ma io avevo già aggiunto il campo `offertelavoro`.`OFFERTA_LINK_SITO_PARIOPP`, non sarebbe meglio usare quest'ultimo, in modo da rimandare gli utenti al ns. sito, che farà poi da gateway verso gli annunci? Così sarebbe potenzialmente possibile tenere traccia del numero di click, ed altro.

@Tpierluigi per risolvere la limitazione della root del webserver, vuoi che crei una tabella `config` sul DB, dove salvare eventuali configurazioni? Per il momento vi inserirei solamente l'uri del sito.
Così la vista se lo prende da lì ed eliminiamo il problema. Che ne dici?

**Comment by Tpierluigi** [comment]
@TBuc potrebbe essere una soluzione, così come quella di valorizzare una costante ulteriore nel file _settings.php_ presente nella root del progetto. Le due alternative le ritengo abbastanza equivalenti, scegli pure quella che preferisci di più.

**Comment by alex-danieli** [comment]
Potevate aggiungermi ... visto che vedo solo ora questa issue -.- ... la soluzione + veloce è comporla in automatico l'url visto che è "predicibile" e quindi non necessita un campo in db ... per comporla basta comporre l'indirizzo http://........./lavoro/index.php?odl_from=local&mode=detail&jobkey=<id tabella offerte lavoro>

**Comment by TBuc** [comment]
@alex-danieli ma tu ti occupi di RSS?

@Tpierluigi ho creato:
- la tabella `config`
- la funzione `GET_WEBSITE_URI()`
- la funzione `GET_WEBPAGE_OFFERTELAVORO_QUERY()`
- la funzione `GET_WEBPAGE_AGENDAEVENTI_QUERY()`

e ho modificato la vista vRSSFEEDS di conseguenza. Ora genera automaticamente i link al sito.

Solo è sorto un problema: l'RSS non viene generato in quanto manca un `htmlentities`. L'ho aggiunto e committato: gentilmente qualcuno può caricare il nuovo file RSS.php sul server? @Tpierluigi @klleshi 
Poi basta verificarne il funzionamento, ma dovrebbe essere tutto OK.

**Comment by alex-danieli** [comment]
<link><![CDATA[" . $array['Link'] . "]]></link>
htmlentities penso serva a poco :D

**Comment by NicolaFrx** [comment]
ora funziona così, grazie @alex-danieli @TBuc

**Comment by TBuc** [comment]
@alex-danieli hai ragione, con CDATA si risolve meglio :-)

@NicolaFrx yeah :dancer:
Sto lavorando e non posso connettermi via VPN; posso quindi considerare l'RSS testato e funzionante?

**Comment by alex-danieli** [comment]
Diciamo funziona per quello che abbiamo potuto testare ...
Le ultime offerte di lavoro che ho caricato vengono visualizzate e il link generato è corretto, quindi per me è OK

**Comment by NicolaFrx** [comment]
Si si dovrebbe andare bene

**Comment by TBuc** [comment]
OK. Anche gli eventi vengono visualizzati correttamente?

**Comment by NicolaFrx** [comment]
Si il feed è funzionante

**Comment by NicolaFrx** [comment]
non ho aggiunto il bando che avevi proposto, che sia da mettere?

**Comment by TBuc** [comment]
@NicolaFrx Ottimo.
Per il bando: dato che è scaduto, direi di no. Se vuoi discuterne in modo più esteso, magari riapri l'issue dedicato. Questo lo chiudo in quanto risolto.
