### ISSUE TITLE
account admin

### ISSUE THREAD

**Issue by simonix93** [InformaticaSaraLei/ProgettoSito#63]
salve,
a noi del gruppo videointerviste & fotogallery ci servirebbe un account admin per provare il form di inserimento e sistemare i link delle foto. E' disponibile un account?

**Comment by klleshi** [comment]
Non è ancora disponibile, appena sarà pronto vi avvertiamo.

**Comment by klleshi** [comment]
Creato account admin.
Quando siete pronti vi mando la password (ditemi voi come mandarla). 
Ricordiamo che il campo ISADMIN della tabella utenti  è di tipo TINYINT
Il 16/01/2015 17:13, Simone Vitiello ha scritto:

**Comment by simonix93** [comment]
l'account che mi hai inviato non funziona. Non mi da i permessi per accedere alle pagine di amministrazione.

**Comment by klleshi** [comment]
L'avevo sollecitato anche in precedenza,  
Questo succede perché il campo ISADMIN della tabella utenti NON è di tipo booleano ma di tipo TINYINT.
Quindi per “admin”: 
ISADMIN == 1 (intero)

**Comment by klleshi** [comment]
Account admin è stato sistemato ed è funzionante  con le credenziali che vi abbiamo dato. 
Per completare il sito dobbiamo cercare di aggiungere nuovi dati; foto, video, eventi ..
 (nota: tante foto non  sono più disponibile sul nostro sito)

**Comment by simonix93** [comment]
Sistemate le foto e aggiunti due video su richiesta del prof.
