### ISSUE TITLE
Modifica voci menu di navigazione

### ISSUE THREAD

**Issue by snalesso** [InformaticaSaraLei/ProgettoSito#64]
La sezione che si trova nella cartella cultura, in base alle indicazioni del prof, andrebbe rinominata in "testimonianze", e la relativa voce nel menu, che ora si trova in Menu > Opportunità > Testimonianze, dovrebbe essere spostata in Menu > Esperienze > Testimonianze.
Poi piccolo ritocco, la voce Menu > Servizi > Link utili credo sarebbe più corretta se apparisse come Links utili (con la 's'), e magari chiamare il relativo file della pagina "linksutili.html", invece di "utili.html".
Chiedo al gruppo Struttura e Grafica di validare queste proposte.

Grazie e buona domenica.

@fundor333 
@andreafrison 
@MargheritaRossi 
@MBruscagnin

**Comment by fundor333** [comment]
Il cambiamento del nome della cartella è dovuto. 
La posizione nel munù di testimonianze mi pare che fosse comunque sotto opportunità ma poi controllerò.
Scrivere Links in italiano non ha senso in quanto in italiano il plurale di link è link

**Comment by Tpierluigi** [comment]
sto chiudendo gli issue  obsoleti o completati. propongo di chiudere anche questo. @fundor333 per voi va bene?

**Comment by fundor333** [comment]
Nulla in contrario
