### ISSUE TITLE
Foto sparite dalla fotogallery

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#65]
Sono scompare alcune foto della fotogallery. Se potete dare una occhiata grazie

**Comment by klleshi** [comment]
A quando sembra le foto non sono più disponibile su Flickr

Il 18/01/2015 21:32, Matteo ha scritto:

**Comment by simonix93** [comment]
Sono cambiati alcuni link delle foto. Domani provvedo a sistemare il tutto!
