### ISSUE TITLE
Footer e navbar

### ISSUE THREAD

**Issue by andreafrison** [InformaticaSaraLei/ProgettoSito#66]
Bisogna sistemare il posizionamento del footer nella pagina "Eventi" e "Chi siamo".
Inoltre manca nella pagina del gioco, così come è da modificare il colore dello sfondo nella navbar sempre nella pagina del gioco.

**Comment by Tpierluigi** [comment]
sembra che sia stato allineato tutto (chiaramente, la pagina "chi siamo" è da completare..)

**Comment by 842647** [comment]
Riapro per segnalare che su Firefox e Safari per Mac il logo nel footer risulta leggermente sballato:

![Uploading Schermata 2015-02-11 alle 22.56.25.png . . .]()

**Comment by andreafrison** [comment]
E' stato cambiata l'immagine di riferimento senza modificare il relativo css!

**Comment by klleshi** [comment]
Intendi del logo di unive del footer?

Il 11/02/2015 23:07, Andrea ha scritto:

**Comment by andreafrison** [comment]
Si! Ma ora ho sistemato!

**Comment by klleshi** [comment]
@fundor
Hai appena rimodificato il footer (non va bene), pochi minuti fa l'aveva 
sistemato Andrea.

Il 11/02/2015 23:13, Andrea ha scritto:

**Comment by andreafrison** [comment]
@klleshi Ho risistemato e già che c'ero ho modificato colore sfondo navbar gioco!
Dimmi se ci sono ancora problemi!

**Comment by klleshi** [comment]
Colore nabar gioco è OK.
footer.html non va bene, devi rifare come prima

Il 11/02/2015 23:36, Andrea ha scritto:

**Comment by andreafrison** [comment]
Io il logo lo vedo corretto ora!
![schermata 2015-02-11 alle 23 44 28](https://cloud.githubusercontent.com/assets/9364018/6158134/f3159e6e-b247-11e4-98fa-0e264a27869f.png)

**Comment by klleshi** [comment]
Lo vedi corretto perché ho sistemato a mano sul server il percorso di 
img ma vedi i link a sinistra, ce troppo spazio tra di loro

Il 11/02/2015 23:44, Andrea ha scritto:

**Comment by andreafrison** [comment]
Ah si.. okay ti riferisci all'interlinea! Domani faccio sistemare a @fundor333  che ha modificato lui il codice che avevo sistemato.

**Comment by klleshi** [comment]
@andreafrison 
Footer funziona correttamente su tutte le pagine a  parte nella pagina di gioco. Rimangano ancora le linee tra i link alla sinistra. 
I bottoni della dashboard di admin non sono visualizzati correttamente.

**Comment by andreafrison** [comment]
Sistemato il footer del gioco!
Nella dashboard non ho messo mano io.. adesso cerco di trovare una soluzione!

**Comment by klleshi** [comment]
@andreafrison 
Penso che adesso il nostro sito è decisamente miglorato.

**Comment by andreafrison** [comment]
@klleshi Migliorato un po' l'ordine della dashboard

**Comment by andreafrison** [comment]
@klleshi Ho aggiunto qualche componente grafica nella dashboard. Se ci sono problemi segnala pure.
