### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by klleshi** [InformaticaSaraLei/ProgettoSito#67]
RSS ancora non funzionante, cosa vogliamo fare?

**Comment by lzuffellato** [comment]
Esattamente qual è il problema? vedo che nessuna pagina php funziona, fa sempre scaricare il file!

**Comment by lzuffellato** [comment]
Come errore vedo dal testing che mi da "connesso con successoAccess denied for user ''@'localhost' (using password: NO)" quindi immagino che al database si connetta ma non gli dia l'accesso per l'utente?

@TBuc

**Comment by TBuc** [comment]
Leonardo, negativo, sembrerebbe più che non siano stati specificati nome
utente e password. Prova a darci un occhio e poi fammi sapere che al limite
guardiamo assieme.
Il 01/feb/2015 13:03 "Leonardo Zuffellato" <notifications@github.com> ha
scritto:

**Comment by lzuffellato** [comment]
Scusa l'ignoranza ma non mi è molto chiaro che utente serve: vedo che da settings.php sono specificati `define("SETTINGS_USERNAME","pariopp-owner"); define("SETTINGS_PASSWORD","pariopp");` . Per prendere dal database le notizie e stamparle in un file rss dovrebbe bastare un utente utile solo alla connessione al db, giusto?

**Comment by TBuc** [comment]
Esatto
Il 01/feb/2015 15:21 "Leonardo Zuffellato" <notifications@github.com> ha
scritto:

**Comment by klleshi** [comment]
Secondo me, l'errore può essere sulle query effettuati alla vista: 
"vRSSFEEDS".
I campi della vista in questione sono: ID, NOMETAB, NEWS, SNIPPET

Il 01/02/2015 17:23, Antonio Bucciol ha scritto:

**Comment by TBuc** [comment]
Non so, devo vedere con calma.
In ogni caso, non sarebbe meglio creare un file db.php, da includere in tutte le pagine, nel quale definire una funzione che si connetta al DB e restituisca la connessione? Così si evitano problemi..

**Comment by klleshi** [comment]
I parametri del database gli ha già incluso Pierluigi su tutte le 
pagine. Il problema non sta nella connessione al database ma nelle query 
errate e senza nessun controllo.
(prova a vedere il file: www_src/servizzi/RSS.php    la riga 22)

Il 01/02/2015 18:57, Antonio Bucciol ha scritto:

**Comment by TBuc** [comment]
Kastriot, la query è giusta e funziona (in locale sul mio pc), cosa intendi
precisamente?
Io posso connettermi al DB sul server dell'uni per effettuare dei test?
Grazie

Il giorno 1 febbraio 2015 19:10, kastriot lleshi <notifications@github.com>
ha scritto:

**Comment by TBuc** [comment]
Grazie @klleshi per le credenziali.
Ho provato e la query funziona... per me c'è qualche problema nella pagina PHP.

**Comment by klleshi** [comment]
Anch'io penso che il team del RSS deve rivedere bene la parte in PHP

**Comment by TBuc** [comment]
OK allora @lzuffellato attendiamo news da te una volta che avete fatto dei test.

**Comment by Tpierluigi** [comment]
mmm. un po' difficile che funzioni se in riga 16 del file rss.php prima di fare mysql_query c'è un mysql_close...

**Comment by Tpierluigi** [comment]
un altro paio di cose:
1 - se si vuole che funzioni, prima della spedizione dell'header, non ci devono essere echo, altrimenti l'header viene spedito automaticamente come text/html.
2 - i CDATA, meglio se non si mettono in linea, che a far debug diventi isterico.. :-)
3 - se usate accenti e robe varie, bisogna fare un escape con htmlentities() altrimenti il parser non la prende bene..
4 - all'inizio,  aggiungere <?xml version="1.0" encoding="UTF-8" ?>
5 - ma si può usare l'html nella description degli item rss??

ho sistemato, aggiornato in test01  e mandato in github. fatemi sapere se avete ancora effetti speciali..

**Comment by lzuffellato** [comment]
grazie delle correzioni.

**Comment by Tpierluigi** [comment]
prego! :-) io chiuderei la issue, se il resto dell' @InformaticaSaraLei/integrazioneecontrollo non vede altre cose strane..

**Comment by Tpierluigi** [comment]
anzi... ci sarebbero altre due magagne sulla pagina index. c'è il lorem ipsum delle pagine e pezzi del testo di test del template bootstrap. Chi sistema quella pagina? inoltre, la pagina di inserimento news è presente nella directory, ma non gestita nell'amministrazione del sito. in attesa che chi di dovere faccia la dashboard amministrativa, sarebbe da verificare se l'inserimento controlla la sessione, sanitizza l'output dalla form ecc.

**Comment by lzuffellato** [comment]
che la data venga fuori come `Thursday, January 1, 1970 1:33` è un problema delle date dei post, o della conversione di sql? va aggiunto un convertitore in RSS pubDate?

**Comment by emanuela83** [comment]
Per chi usa crome per visualizzare RSS funzionante bisogna aggiungere estensione  RSS Subscription Extension (by Google).

**Comment by lzuffellato** [comment]
ho visto le correzioni di @Tpierluigi sulla parte della newsletter, grazie!
per RSS, che sia da mettere, nella parte della data, `gmdate(DATE_RSS, strtotime($array['data']))` ?
che mi è stato segnalato da @NicolaFrx che non funziona!

**Comment by NicolaFrx** [comment]
Per quanto riguarda la data non saprei, mi sembra una buona idea provare come dici, altrimenti prova con questa

string strftime ( string $format [, int $timestamp = time() ] )

 che mi sembra si avvicini al nostro problema quello esposto qui: http://php.net/manual/en/function.strftime.php

@TBuc 
per quanto riguarda il database, 
-le opportunità culturali inserite quali sarebbero?
-è possibile concatenare "nuova opportunità di lavoro" con la provincia per piacere?
-si può inserire il link relativo all'offerta?

Grazie

**Comment by TBuc** [comment]
@lzuffellato 
scusa se ti rispondo con due giorni di ritardo ma mi era sfuggita l'email di notifica di questo topic.

Per la data: il driver che usi per connetterti al DB è specifico per la tupla <linguaggio,DBMS>: ad esempio, in questo caso, linguaggio=PHP e (R)DBMS=mysql. A livello di tipi, il driver mappa i tipi di dati disponibili da una parte con quelli disponibili (e compatibili) dall'altra. Lo sviluppatore di ogni driver può quindi operare le sue scelte.
Ora, in base al tipo di driver che usi (mysql? mysql_pdo?) il tipo "date" ti viene restituito in un dato formato (consultare specifiche driver per conoscere quale). Tu lo puoi quindi trasformare (e molto probabilmente vorrai farlo) in un altro formato, più leggibile e/o consono al contesto.
Ma a questo punto il DB non c'entra più nulla, in quanto hai un tipo di dato di PHP che vuoi formattare in uno specifico modo: devi quindi vedere quali strumenti fornisce PHP per formattare tale tipo di dato.
Ora, nel caso specifico: il tipo di dato è `date` e vi consiglio di vedervi questa pagina per esempi su come formattare tale tipo (vi sono anche parecchi esempi): http://php.net/manual/en/function.date.php

@NicolaFrx 
hai correttamente consigliato la funzione `strftime`, che è anche più potente di `date(format,date)`, ma per contro è più complessa. A loro basta e avanza usare date() e credo gli risulti anche più semplice.
Per le tue domande, qui non c'entrano: ti rispondo nell'issue apposito.

**Comment by Tpierluigi** [comment]
ma... scusate.. se invece di diventar scemi a vedere come funzionano le date da mysql a php trasformate le date in stringhe direttamente in mysql?
tipo: 
```
SELECT id, nometab, news, snippet, date_format(`data`, '%d / %m / %Y') 
as `data` FROM vRSSFEEDS;
```

dopo se volete giocare con il date_format qui c'è la documentazione:
http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_date-format

**Comment by Tpierluigi** [comment]
poi un'altra cosa: 
il titolo delle varie news è sempre:  "nuova offerta di lavoro"
manca il tag <link> dentro gli item, cliccando sull'articolo così non si va da nessuna parte...

**Comment by TBuc** [comment]
@Tpierluigi così è più semplice, non ci avevo proprio pensato :)
Il 18/feb/2015 23:23 "Tpierluigi" <notifications@github.com> ha scritto:

**Comment by lzuffellato** [comment]
okay seguendo il consiglio di @Tpierluigi ho corretto in 
```
SELECT id, nometab, news, snippet, date_format(`data`, '%a, %d %b %Y %H:%i:%s +0100') as `data` FROM vRSSFEEDS 
```
(seguendo il formato corretto). Spero sia corretto come ho modificato il codice! Appena viene caricato il tutto controllo se funziona

**Comment by klleshi** [comment]
@lzuffellato
Ho appena aggiornato il server test01

Il 19/02/2015 18:28, Leonardo Zuffellato ha scritto:

**Comment by lzuffellato** [comment]
La data mi sembra funzionare! vedo che non sono ordinate però, in effetti manca il sort. Aggiungo order by

**Comment by klleshi** [comment]
La data la metterei in ordine decrescente, cioè l'ultima data all'inizio no?

Il 19/02/2015 19:04, Leonardo Zuffellato ha scritto:

**Comment by vpagini** [comment]
Certo! Ci era scappato, sistemiamo prima possibile!
________________________________
Da: kastriot lleshi<mailto:notifications@github.com>
Inviato: ‎19/‎02/‎2015 19:15
A: InformaticaSaraLei/ProgettoSito<mailto:ProgettoSito@noreply.github.com>
Oggetto: Re: [ProgettoSito] RSS (#67)

La data la metterei in ordine decrescente, cioè l'ultima data all'inizio no?

Il 19/02/2015 19:04, Leonardo Zuffellato ha scritto:
>
> La data mi sembra funzionare! vedo che non sono ordinate però, in
> effetti manca il sort. Aggiungo order by
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/InformaticaSaraLei/ProgettoSito/issues/67#issuecomment-75103348>.
>



---
