### ISSUE TITLE
Pagina di Gioco

### ISSUE THREAD

**Issue by klleshi** [InformaticaSaraLei/ProgettoSito#68]
Alcune osservazioni  

- Il codice va ripulito dalle parti non utilizzabili (interrogazione database …).
- Come sollecitato da @andreafrison, il colore dello sfondo di navbar va allineato con il resto del sito
- Nel footer va tolto il nome dei autori e va inserito il nome del sito tipo:
 “Copyright Informatica sarà lei!  2014”

**Comment by 842647** [comment]
@klleshi ora sono via per lavoro, rientro in serata e provvedo a sistemare.
Dove faccio le modifiche? Sul server test01 o sul sorgente che c'è in github?

**Comment by klleshi** [comment]
@842647 
Sul sorgente che ce i github. Sul server test01 lo sistemiamo noi.

**Comment by 842647** [comment]
Rimosso dump sql..

**Comment by 842647** [comment]
Rimossa pagina interroga db

**Comment by 842647** [comment]
@klleshi sto provando nel mio pc e funziona, verificate anche voi per favore, nell'ultimo commit ho aggiornato il footer e parte dell'header, ora aggiorno il menu!

**Comment by 842647** [comment]
@klleshi aggiornato anche menù, test su mio pc va, provate anche voi!

**Comment by 842647** [comment]
@klleshi non ho più ricevuto tuoi feedback

**Comment by klleshi** [comment]
La navbar presenta dei problemi sulla dimensione, copre quasi tutta la 
pagina. Lo puoi verificare su http://test01.dsi.unive.it

Il 02/02/2015 13:37, 842647 ha scritto:

**Comment by 842647** [comment]
@klleshi ora sono in ufficio, quando rientro vedo di capire che problemi ci sono! ;)

**Comment by 842647** [comment]
@klleshi guardando sembra essere la classe logo che manca, ho aggiornato, riesci a provare?

**Comment by 842647** [comment]
@klleshi Mi sono accorto che il CSS del footer non va bene, quello lo sistemo appena arrivo a casa..

**Comment by klleshi** [comment]
Ok, la navbar va bene, appena posso lo carico sul server

Il 02/02/2015 18:26, 842647 ha scritto:

**Comment by klleshi** [comment]
@842647
Ho caricato le modifiche del gioco sul server e la navbar è apposto.

(Sembra che il colore dello sfondo di navbar non sia identico a quello 
della home page, forse è una mia impressione, magari il team di Grafica 
ci può aiutare)


Il 02/02/2015 18:26, 842647 ha scritto:

**Comment by 842647** [comment]
@klleshi è così, ho aggiornato il css inserendo il colore giusto della navbar, grazie.

**Comment by 842647** [comment]
@klleshi appena puoi verifica

**Comment by 842647** [comment]
@klleshi ora vedo di sistemare anche il footer

**Comment by 842647** [comment]
@klleshi sistemato anche il footer, appena puoi aggiorna e prova che casomai sistemo..

**Comment by klleshi** [comment]
@842647
La navbar è Ok.
Il footer non è esteso su tutta la larghezza, forse il contenuto 
(appunto del footer) prima andrebbe inserito dentro un div.


Il 02/02/2015 22:14, 842647 ha scritto:

**Comment by 842647** [comment]
@klleshi in che senso?

**Comment by klleshi** [comment]
@842647
Non prende tutta la larghezza disponibile come la navbar (vedi su server 
test01)

Il 02/02/2015 23:13, 842647 ha scritto:

**Comment by 842647** [comment]
@klleshi visto, prova ora!

**Comment by andreafrison** [comment]
Le indicazioni per il footer corretto sono in un mio issue!

**Comment by 842647** [comment]
@andreafrison ora leggo, purtroppo abbiamo fatto il gioco su un template diverso da quello base e con versioni diverse di jquery, vedo di sistemarle un po' alla volta.
Nell'ultimo update comunque penso di aver parzialmente risolto

**Comment by 842647** [comment]
@klleshi è possibile avere accesso diretto a test01? Così posso provare direttamente le modifiche che faccio.. Ora vado a letto e quindi fino a domani non potrò essere di aiuto..

**Comment by 842647** [comment]
@klleshi @andreafrison chiedo il vostro aiuto per cercare di sistemare il footer.

**Comment by klleshi** [comment]
@842647
Guarda che il footer è apposto, (prova a vedere su test01)

Il 03/02/2015 21:42, 842647 ha scritto:

**Comment by 842647** [comment]
@klleshi ho provato anche a cancellare la cache ma a me non sembra apposto..

Questo è il footer (mancano le icone social e c'è una barra bianca sotto)

![schermata 2015-02-03 alle 21 45 34](https://cloud.githubusercontent.com/assets/9413437/6029033/14340ec4-abee-11e4-95bf-7f15c7d87752.png)

Mentre questo è il footer di un'altra pagina:

![schermata 2015-02-03 alle 21 46 43](https://cloud.githubusercontent.com/assets/9413437/6029048/2b008524-abee-11e4-99d8-e009112e398f.png)

Chiedo supporto a te o al team grafico per sistemare quelle 2/3 cosine mancanti..

**Comment by klleshi** [comment]
Si è vero, la larghezza è ok ma le icone dei social mangano.

Il 03/02/2015 21:47, 842647 ha scritto:

**Comment by 842647** [comment]
E c'è un problema di allineamento nel li di links, ma non essendo super ferrato con CSS chiedo supporto a @andreafrison o @fundor333

**Comment by fundor333** [comment]
Sistemato footer

**Comment by 842647** [comment]
Grazie :+1:

**Comment by 842647** [comment]
@fundor333 pensavo fosse un problema di cache, ma continuo a visualizzare in maniera errata il footer.. :disappointed:

**Comment by fundor333** [comment]
Io lo vedo corretto... PS: io non posso caricarlo su test01, lo ho provato in locale

**Comment by 842647** [comment]
Ok, allora penso sia quello il motivo, grazie e scusami :+1:

**Comment by 842647** [comment]
@fundor333 ho visto ed ora è ok, però i li sotto link non risultano allineati come nelle altre pagine.
Ho provato in locale a dare float left, ma non cambia, puoi supportarmi?

**Comment by fundor333** [comment]
@842647 Fatto aspettiamo solo l'upload. Ne ho anche aprofittato per fare pulizia di file inutili e doppi
