### ISSUE TITLE
Errore DB tabella offertelavorotags

### ISSUE THREAD

**Issue by alex-danieli** [InformaticaSaraLei/ProgettoSito#70]
Ciao,
mi son accorto di un errore nella definizione della tabella offertelavorotags
FK_TAG
REFERENCES `pariopp`.`media`(`id`)
non è corretto ... deve referenziare pariopp.tags('id')
ed 
FK_OFFERTE
REFERENCES `pariopp`.`tags`(`id`) 
dovrebbe referenziare  pariopp.offertelavoro('id')

.... una cosa del genere dovrebbe essere 

  ADD CONSTRAINT `offertelavorotags_ibfk_2` FOREIGN KEY (`FK_OFFERTE`) REFERENCES `offertelavoro` (`ID`) ON UPDATE CASCADE,
  ADD CONSTRAINT `offertelavorotags_ibfk_1` FOREIGN KEY (`FK_TAG`) REFERENCES `tags` (`ID`) ON UPDATE CASCADE;

----------------- SQL funzionante per la tabella offertelavorotags della mia versione locale modificata
--
-- Struttura della tabella `offertelavorotags`
--
CREATE TABLE IF NOT EXISTS `offertelavorotags` (
  `FK_TAG` int(10) unsigned NOT NULL,
  `FK_OFFERTE` int(10) unsigned NOT NULL,
  PRIMARY KEY (`FK_TAG`,`FK_OFFERTE`),
  KEY `offertelavorotags_ibfk_2` (`FK_OFFERTE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Limiti per la tabella `offertelavorotags`
--
ALTER TABLE `offertelavorotags`
  ADD CONSTRAINT `offertelavorotags_ibfk_2` FOREIGN KEY (`FK_OFFERTE`) REFERENCES `offertelavoro` (`ID`) ON UPDATE CASCADE,
  ADD CONSTRAINT `offertelavorotags_ibfk_1` FOREIGN KEY (`FK_TAG`) REFERENCES `tags` (`ID`) ON UPDATE CASCADE;

Grazie

**Comment by TBuc** [comment]
@alex-danieli hai perfettamente ragione, grazie.
@klleshi ci sono dati nella tabella 'offertelavorotags'? Perchè altrimenti la ridefinisco ex-novo, anzichè scrivere delle 'alter...'.

**Comment by klleshi** [comment]
Non ci sono dati sulla  tabella 'offertelavorotags'

**Comment by alex-danieli** [comment]
Bon :D grazie ad entrambi ... per me potete brasare tutto nessun dato utile per ora :D

**Comment by TBuc** [comment]
@klleshi ma per caso non è possibile far impostare una NAT per connettersi al DB usando MySql Workbench?
PHPMyAdmin è semplicemente indecente...

**Comment by TBuc** [comment]
Problema corretto. Ho aggiornato l'istanza sul server test01.
Il codice aggiornato è committato.

@alex-danieli grazie ancora.

**Comment by Tpierluigi** [comment]
@TBuc  NAT? non so, ma non credo che te la facciano fare.. ho idea che non lo abilitino per problemi di security...

**Comment by TBuc** [comment]
Mah, se è in una qualche DMZ magari lo fanno... Non perdeteci tempo apposta
che non credo ne valga la pena, ormai non resta molto da fare. Solo se
avete occasione di sentirli per altre cose, magari provate a sentire che ne
dicono...
Il 04/feb/2015 00:05 "Tpierluigi" <notifications@github.com> ha scritto:

**Comment by alex-danieli** [comment]
Per quanto riguarda l'edit degli index phpMyAdmin permette di aggiornarli direttamente da interfaccia ... da Structure->Indexes->Edit come evidenziato con questa tabella di esempio

![index_edit](https://cloud.githubusercontent.com/assets/6577970/6037111/bbf626c2-ac4f-11e4-8105-76516e1db08f.png)

**Comment by TBuc** [comment]
Alex sì, sono io che ho una certa avversione per un uso così esteso delle
interfacce grafiche in questo ambito.
Il 04/feb/2015 09:26 "alex-danieli" <notifications@github.com> ha scritto:

**Comment by alex-danieli** [comment]
Ho appena fatto un collaudo della mia sezione ed il problema dei tag permane ... nel mio ambiente di sviluppo funziona tutto.

AleXD

**Comment by TBuc** [comment]
@alex-danieli sì scusa, errore mio: adesso l'ho corretto.

Ho visto che in locale lavoravi in latin1; attento che il DB di produzione usa charset UTF8.

**Comment by alex-danieli** [comment]
Si si nessun problema quello era uno screenshot di un altro DB :-)
Il 06/feb/2015 18:37 "Antonio Bucciol" <notifications@github.com> ha
scritto:
