### ISSUE TITLE
Video del prof

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#71]
Al gruppo Foto/video e al gruppo di Coordinamento: 
la homepage è finita mancano i video del prof. Appena sono stati caricati sull'account youtube possiamo avere i link per incorporarli nel sito? Thanks

**Comment by andreafrison** [comment]
@msottana @gcorsi @KarinaZinchenko @enricoabiti

**Comment by enricoabiti** [comment]
Noi del gruppo Foto/Video non abbiamo ricevuto nulla dal prof

**Comment by gcorsi** [comment]
Ciao!
Abbiamo contattati il professore, tirerà fuori il materiale!
Giulia

Inviata dal mio Windows Phone
________________________________
Da: Enrico<mailto:notifications@github.com>
Inviato: ‎04/‎02/‎2015 15:07
A: InformaticaSaraLei/ProgettoSito<mailto:ProgettoSito@noreply.github.com>
Cc: gcorsi<mailto:giuliacorsi@outlook.it>
Oggetto: Re: [ProgettoSito] Video del prof (#71)

Noi del gruppo Foto/Video non abbiamo ricevuto nulla dal prof

---
