### ISSUE TITLE
Pagina  delle  Testimonianze (CULTURA)

### ISSUE THREAD

**Issue by emanuela83** [InformaticaSaraLei/ProgettoSito#73]
Bisogna dare una dimensione fissa ai riquadri.

**Comment by NicolaFrx** [comment]
Ciao a tutti
mi chiedevo come mai non si parla delle donne che hanno fatto la storia dell'informatica come Ada Lovelace ecc..
Mi sembrava fossero state trattate molto nelle presentazioni e che abbiano un buon ruolo informativo

**Comment by emanuela83** [comment]
#Pagina Testimonianze
Il footer della pagina non è uniforme con le altre pagine. 
"Copyright © Informatica sarà lei! 2014"  deve essere spostato  al centro della pagina.

**Comment by fundor333** [comment]
Sistemato il footer

**Comment by Tpierluigi** [comment]
confermo. i due footer ora sono uguali. se volete potete chiudere.
