### ISSUE TITLE
Segnalazioni per Grafica e struttura

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#74]
Segnalate qui i problemi riscontrati per la grafica e la struttura del sito

**Comment by gcorsi** [comment]
Il footer non dovrebbe essere tolto nella versione mobile? A noi il Pitta diceva di toglierlo...

**Comment by klleshi** [comment]
Nel footer ci sono i link dei social e quindi a mio parere deve rimanere 
anche nella versione mobile.

Il 04/02/2015 20:23, gcorsi ha scritto:

**Comment by andreafrison** [comment]
Inoltre sempre nel footer, nella parte destra andranno inseriti i vari loghi (quando ci verranno forniti i vettoriali o qualcosa di decente).  Quindi è fondamentale che il footer sia presente in entrambe le versioni.
