### ISSUE TITLE
PROBLEMA FOTOGALLERY- studentesse per la home

### ISSUE THREAD

**Issue by MargheritaRossi** [InformaticaSaraLei/ProgettoSito#75]
Ci servirebbero delle foto di ragazza mentre studiano che abbiano un formato decente, perchè, come da verbale, dobbiamo inserirle nel carousel della home. 
Cortesi ha detto che si può chiedere alle ragazze di scienze ambientali se vogliono fingersi studentesse di informatica e fare le foto con loro. L'ideale sarebbe avere un paio di foto di ragazze che studiano in biblioteca con qualche nostro libro, qualche foto di ragazze con i portatili davanti, e volendo anche in giradino basta che abbiano qualcosa che faccia capire che fanno informatica. Attenzione, bisogna far firmare loro anche una liberatoria per l'utilizzo di quelle foto, che non andiamo nei casini. Più foto abbiamo meglio è, cosi possiamo fare una piccola cernita. Grazie

**Comment by enricoabiti** [comment]
Per le foto stiamo provvedendo però sono poche le ragazze che si concedono

**Comment by emanuela83** [comment]
#MargheritaRossi in questo progetto quante ragazze ci sono? Non si può organizzare che ci troviamo tutte al università un giorno e  si fanno un paio di foto in biblioteca.

**Comment by MargheritaRossi** [comment]
la cosa non è fattibile, noi siamo poche e non tutte riescono più a venire all'università perché al terzo anno hanno quasi tutte (tranne la sottoscritta) finito. La cosa migliore è coinvolgere quelle di scienze e fare un paio di foto (anche per una questione di "ricambio facce" che se no son sempre le stesse)
