### ISSUE TITLE
#Sezione CHI SIAMO

### ISSUE THREAD

**Issue by emanuela83** [InformaticaSaraLei/ProgettoSito#78]
Bisogna sistemare il FOOTER della pagina About. Deve essere uniforme con le altre pagine.

Grazie 
Gruppo Integrazione e Controllo

**Comment by fundor333** [comment]
@emanuela83 visto che abbiamo problemi di server mi assicurate che la versione definitiva del sito è quella di github? in questo modo facciamo i test in locale per sistemare i vari footer (sono più pagine con questo problema)

**Comment by Tpierluigi** [comment]
ah, allora non sono solo io, a non riuscire più ad accedere a test01!
non mi risponde più neanche al ping...
comunque, fino a ieri che io sappia quello che c'era in test01 corrispondeva a quanto caricato in github..

**Comment by fundor333** [comment]
Per ora i server hanno problemi ma in locale il problema è stato risolto
