### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#79]
MAnca completamente il contenuto. Chiedo a @gcorsi @msottana se è stato fatto qualcosa a riguardo

**Comment by gcorsi** [comment]
Si lo ho io, volevo caricarlo una volta finito ma ci mancano le foto/gli stemmi dei gruppi, se volete carichiamo intanto quello che c'è...

Inviata dal mio Windows Phone
________________________________
Da: Matteo<mailto:notifications@github.com>
Inviato: ‎08/‎02/‎2015 16:51
A: InformaticaSaraLei/ProgettoSito<mailto:ProgettoSito@noreply.github.com>
Cc: gcorsi<mailto:giuliacorsi@outlook.it>
Oggetto: [ProgettoSito] About Us (#79)

MAnca completamente il contenuto. Chiedo a @gcorsi @msottana se è stato fatto qualcosa a riguardo

---
Reply to this email directly or view it on GitHub:
https://github.com/InformaticaSaraLei/ProgettoSito/issues/79

**Comment by MargheritaRossi** [comment]
@gcorsi fai una cosa carica intanto quello che hai, cosi se c'è qualche problema ci possiamo pensare con calma

**Comment by gcorsi** [comment]
Ok!

________________________________
Da: MargheritaRossi<mailto:notifications@github.com>
Inviato: ‎08/‎02/‎2015 19:08
A: InformaticaSaraLei/ProgettoSito<mailto:ProgettoSito@noreply.github.com>
Cc: gcorsi<mailto:giuliacorsi@outlook.it>
Oggetto: Re: [ProgettoSito] About Us (#79)

@gcorsi fai una cosa carica intanto quello che hai, cosi se c'è qualche problema ci possiamo pensare con calma

---
