### ISSUE TITLE
Modifiche Gioco dopo verbale

### ISSUE THREAD

**Issue by 842647** [InformaticaSaraLei/ProgettoSito#82]
Ho visto che nel verbale venivano elencate alcune modifiche da fare, ma ho visto che @fundor333 ha già messo mano, giusto per capire è rimasto qualcosa da modificare?

**Comment by emanuela83** [comment]
e stato ripristinato la versione precedente. Dovrebbe andare bene cosi.

Il giorno 9 febbraio 2015 21:33, 842647 <notifications@github.com> ha
scritto:

**Comment by 842647** [comment]
Come mai è stata ripristinata? @emanuela83

**Comment by fundor333** [comment]
Alcune delle modifiche per far funzionare il footer buggavano la grafica del sito-> siamo tornati indietro e rifatto le modifiche per il footer in modo che non influiscano sul gioco

**Comment by 842647** [comment]
Ma quindi, non ho capito, devo fare le modifiche o sono già state fatte? @fundor333 @emanuela83

**Comment by fundor333** [comment]
A meno che non salti fuori qualcosa i problemi venuti fuori a riunione risultano risolti
