### ISSUE TITLE
Aiuto in Javascript

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#83]
Stiamo cercando di eseguire una funzione al ridimensionamento della pagina. Qualcuno può aiutare? Non è un bug ma sarebbe meglio avere questa possibilità implementata

**Comment by Tpierluigi** [comment]
mmm...

puoi provare un 
```javascript
window.onresize(function(){
  //codice che vuoi eseguire
});
```

oppure, se hai più di un gestore evento da eseguire, usare addEventListener, che chiaramente per exploder < 9 non c'è ed è sostituito da  attachEvent. quindi devi fare prima il controllo, tipo:

```javascript
if (window.addEventListener){
  //uso addeventlistener
} else {
  //uso attachEvent
}
```

**Comment by fundor333** [comment]
Aggiungendo il codice di @Tpierluigi risulta efficace (segnala l'aggiornamento delle dimensioni) ma segnala che     

var padding = ($(class_string).css("padding")).split("px");

è non definito

**Comment by Tpierluigi** [comment]
mi sa che stai facendo una closure.
togli via le parentesi più esterne alla $; cosi:

$(class_string).css("padding").split("px");

**Comment by fundor333** [comment]
Cambia nulla. Se vuoi provare il file è resize.js

**Comment by Tpierluigi** [comment]
si perchè sono definiti padding-left, padding-top eccetera..

**Comment by Tpierluigi** [comment]
aspetta che do un'occhiata..

**Comment by Tpierluigi** [comment]
fai un pull dell'ultima versione e dimmi se era quello che volevi fare...

**Comment by fundor333** [comment]
No. Non fa ne quello che prima faceva (allineare le dimensioni per riga di ogni riquadro) ne quello che volevo che facesse (ridimensionare ogni riquadro per riga se ridimensioni la pagina)

**Comment by alex-danieli** [comment]
Prova con questo css

.equalrow{
    margin-bottom: -99999px;
    padding-bottom: 99999px;
    background-color:#efefef;
}

#equalheight {
    overflow: hidden; 
}

..... 
da applicare ad una struttura html del tipo come questa

   <div id="equalheight">      
  
          <div class="col-XY .... equalrow">
              ...
          </div>  
  
          <div class="col-XY .... equalrow">
              ...
          </div> 
   </div>

c'è un esempio uguale uguale qua http://www.bootply.com/92230

Spero sia utile

**Comment by fundor333** [comment]
Mi da problemi quindi ho sistemato la cosa da html. Non è bello ma almeno è funzionale
