### ISSUE TITLE
Foto per carosello !URGENTE!

### ISSUE THREAD

**Issue by andreafrison** [InformaticaSaraLei/ProgettoSito#85]
Come già richiesto in una precedente issue necessitiamo di almeno 3 foto per il carosello di alta qualità con dimensione almeno 1900x1080px.
Inoltre (sempre come già scritto) le foto dovreanno essere studiate in maniera tale da evitare problemi di questo tipo (teste mozzate e logo non visibile):
![f](https://cloud.githubusercontent.com/assets/9364018/6131585/575820be-b14d-11e4-9dff-30b02087f6e2.JPG)
Grazie per la collaborazione

@gruppofoto/video

**Comment by enricoabiti** [comment]
C'è un problema di fondo sul carosello... mettendo le immagini attraverso l'attributo css background-image, l'unico modo per adattare l'immagine al contenitore è background-size... l'attributo di background-size che usate voi è "cover" che scala l'immagine in base all'larghezza del contenitore in modo da coprirlo... visto che l'altezza del contenitore nel carosello varia in base alla dimensione della finestra del browser, foto e contenitore difficilmente avranno la stessa proporzione della dimensione
Non so se mi sono spiegato bene...Hai intuito quello che voglio dire?

Se vuoi invece di 1900x1080 provo a fare 3000x1080

**Comment by andreafrison** [comment]
@enricoabiti ma va benissimo il 1900x1080 il discorso è che servirebbe fossero prese "da più distante" in modo che il viso sia proprio nel mezzo della foto (sappiamo che può sembrare brutto per una foto.. ma l'effetto viene decentemente nel carosello).
La foto dovrebbe risultare tipo questa (chiaramente con le gambe!)
![slide-ragazza1b](https://cloud.githubusercontent.com/assets/9364018/6138041/078cb230-b17e-11e4-835d-57d1e4b5c2be.jpg)
Grazie

**Comment by enricoabiti** [comment]
@andreafrison Eh ho capito io ma non riesco a rifare la foto

**Comment by andreafrison** [comment]
Siamo andati di GIMP e Photoshop e abbiamo creato delle nuove immagini.
