### ISSUE TITLE
Caricamento video

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#86]
Ho parlato con Cortesi e mi ha detto che i video sono ancora in elaborazione e intanto dobbiamo caricare il video presente nella pagina della wiki mostratoci come esempio di intervista

**Comment by andreafrison** [comment]
Quindi c'è bisogno che venga caricato sul canale di youtube di informatica sarà lei!

**Comment by enricoabiti** [comment]
Lo stiamo caricando

**Comment by andreafrison** [comment]
Grazie così possiamo iniziare a popolare la pagina

**Comment by simonix93** [comment]
Ecco il link: https://www.youtube.com/watch?v=cIm7gK5_Zt0

**Comment by andreafrison** [comment]
Grazie

2015-02-11 17:44 GMT+01:00 Simone Vitiello <notifications@github.com>:

**Comment by andreafrison** [comment]
Ma è il video originale in 480p? Oppure è ancora in fase di elaborazione?

**Comment by simonix93** [comment]
Sì è 480p

**Comment by andreafrison** [comment]
Potrei chiedervi gentilmente di selezionare (se vi sembra più decente) un altro fotogramma del video su youtube? In quanto quello attuale ha un probelma sul lato destro!
https://i.ytimg.com/vi/cIm7gK5_Zt0/mqdefault.jpg

**Comment by simonix93** [comment]
Ok ho cambiato frame. Dovrebbe andare bene ora.

**Comment by andreafrison** [comment]
Grazie! Attendo che youtube aggiorni!

**Comment by simonix93** [comment]
io su test01 lo vedo già aggiornato!

**Comment by MargheritaRossi** [comment]
appena arrivata una mail di cortesi per le videointerviste. Il messaggio dice "sono ancora non in formato definitivo, ma potete caricarle sulla home page. Potreste mettere come icona di accesso un bottone (di vari colori) con su scritto: "Io sono informatica"... ma vedete voi!" il link è questo https://filesender.garr.it/?vid=08ee2322-b60e-82a9-da13-00007ca16f10

**Comment by enricoabiti** [comment]
Abbiamo caricato i video, questi sono i link...
https://www.youtube.com/watch?v=1QhvmJyNiik
https://www.youtube.com/watch?v=y0iX83Ilkdc
https://www.youtube.com/watch?v=Cxd-P9JlFs4
https://www.youtube.com/watch?v=OTwY0dyLOn8
https://www.youtube.com/watch?v=KirkX3Q30GM

**Comment by MargheritaRossi** [comment]
Ho domandato a cortesi se dobbiamo aspettarcene altri, in caso vi avviso @enricoabiti

**Comment by enricoabiti** [comment]
Ok perfetto.. comunque ho sistemato la descrizione sui video di cortesi se a qualcuno serve

**Comment by simonix93** [comment]
@andreafrison ho visto che hai preso le descrizioni dei nostri video ma non erano ancora aggiornate. Se vuoi ora puoi mettere quelle finali.

**Comment by andreafrison** [comment]
@simonix93 Grazie! Li avevo messi intanto come segnaposto semi-definitivo!
