### ISSUE TITLE
Creazione DB

### ISSUE THREAD

**Issue by TBuc** [InformaticaSaraLei/ProgettoSito#87]
Come richiesto da @klleshi , ho verificato il funzionamento della creazione da zero del DB, nel caso in cui la Regione volesse poi ricrearlo ex-novo suoi propri server anzichè esportarlo.

Non potendo creare nuovi DB sul server dell'uni, ho testato su un server simile (minor release 36 anzichè la 41 del server uni) utilizzando phpMyAdmin.

Funziona tutto liscio. Si sarebbe potuto arrabbiare negli script 2bis e 5, se non ci fosse stato alcun DB selezionato. Ho esplicitato anche in questi file il nome del DB, così è a prova di errore.

@klleshi dimmi se ti è venuto in mente qualche altro problema/test, altrimenti per quanto mi riguarda questo issue è chiudibile.

**Comment by klleshi** [comment]
@TBuc
Visto che il tuo test è stato OK penso che possiamo chiudere questo issue.
Una piccola cosa: sarebbe corretto che alla fine del progetto potessimo 
eliminare le tabelle non utilizzate dal DB.

Il 11/02/2015 17:10, Antonio Bucciol ha scritto:

**Comment by MargheritaRossi** [comment]
Se per voi va bene chiuderei questa iussue, non penso abbia più motivo di esistere se è tutto a posto.

**Comment by TBuc** [comment]
@MargheritaRossi: kleshi attendeva una mia risposta.

@klleshi: ho fatto un po' di pulizia, eliminando le tre tabelle relative al gioco, che mi avevi confermato che non servono più.
Vi sono altre tabelle vuote, ma non so se vadano rimosse anch'esse. Si tratta di:
- agendaeventi
- esperienzedonne
- mediatags (come mai è vuota se ci sono dei media??)
- offertelavorostorico
- opportunitaculturalicarriera
- opportunitaculturalipersone

i vari team interessati sanno dirmi cosa fare di queste tabelle? Ovvero: le userete SI/NO/FORSE? Così eventualmente faccio pulizia. @italo3600 @micheleminighin @snalesso @alex-danieli

**Comment by klleshi** [comment]
@Tbuc
OK, hai fatto bene ad eliminare le tabelle riguarda il gioco. Per le 
altre tabelle sollecitate da te aspettiamo un po i gruppi interessati: 
@italo3600 <https://github.com/italo3600> @micheleminighin 
<https://github.com/micheleminighin> @snalesso 
<https://github.com/snalesso> @alex-danieli 
<https://github.com/alex-danieli>

Il 12/02/2015 17:07, Antonio Bucciol ha scritto:

**Comment by snalesso** [comment]
Confermo che potete togliere le tabelle relative alla sezione testimonianze, si è scelto di inserire i dati direttamente nella pagina

**Comment by TBuc** [comment]
@snalesso la sezione testimonianze sarebbe "Esperienze donne"?

Gli altri team: nessuna risposta?

**Comment by TBuc** [comment]
OK intanto ho rimosso 'esperienzedonne'.

**Comment by klleshi** [comment]
Vi segnalo che la VPN è funzionante. 
@TBuc le tabelle:
agentaeventi:  hanno confermato che cominciano a popolare da domani. 
ofertalavorostorico: @alex-danieli può dirci cosa fare.
opportunitaculturalicarriera: hanno usato pagine statiche
opportunitaculturalipersone: hanno usato pagine statiche
mediatags: ?

**Comment by simonix93** [comment]
noi del team videointerviste & fotogallery avevamo già comunicato tempo fa a @TBuc che le tabelle tags (e di conseguenza mediatags) non le usavamo più.

**Comment by TBuc** [comment]
@simonix93 la tabella `tags` viene usata anche da altri.
Per la tabella `mediatags`: l'avevo temporaneamente lasciata lì nel caso in cui aveste cambiato idea. A questo punto, visto che siamo in dirittura d'arrivo, effettivamente la posso cancellare. Stasera provvedo.
