### ISSUE TITLE
Pagina About e Testimonianze

### ISSUE THREAD

**Issue by fundor333** [InformaticaSaraLei/ProgettoSito#88]
È stato riscontrato che utilizzando i browser che fanno uso di WebKit lo script che gestisce la formattazione dei div delle pagine About e Testimonianze (per capirci quello che dovrebbe rendere della stessa misura tutti i riquadri della stessa riga) non funziona correttamente (sovrappone tutti gli elementi del div) per cui è stato modificato lo script per non funzionare con i suddetti browser. Verrà sistemato se si riesce, in quanto è solo un piccolo bug estetico che non compromette l'usabilità del sito.

Se siete interessati ai tentativi di messa a punto del JS il lavoro viene eseguito sul branch "correzioneJS"

**Comment by giorgiabosello** [comment]
Abbiamo notato che è un bug grafico perché a volte va, a volte no. Se si apre sbagliato, con CTRL+F5 si vede bene. 
Non trovavamo il problema e pensavamo di tentare di risolvere con js a parte, ma se c'è già un file, allora meglio. Magari proviamo a darci un occhio.

**Comment by fundor333** [comment]
Il discorso è questo: per ora quando rileva il motore problematico non esegue lo script per cui non appare il bug grafico. Sto ora cercando un sistema per farlo funzionare correttamente

**Comment by fundor333** [comment]
Trovato e risolto il problema: era causato dall'errata esecuzione dello scritp: in webkit viene eseguito prima del caricamento delle immagini. È bastato quindi cambiare il momento di esecuzione dello script a DOPO il caricamento delle immagini
