### ISSUE TITLE
Problemi Gioco

### ISSUE THREAD

**Issue by 842647** [InformaticaSaraLei/ProgettoSito#89]
Dopo le modifiche il footer e il container della pagina hanno problemi.. Risolvo io o chi ha messo mano?

**Comment by fundor333** [comment]
Che problemi?

**Comment by 842647** [comment]
Schermata 2015-02-11 alle 22.30.40
Schermata 2015-02-11 alle 22.30.46

**Comment by klleshi** [comment]
Sistemato img di unive del footer

Il 11/02/2015 22:31, 842647 ha scritto:

**Comment by 842647** [comment]
![schermata 2015-02-11 alle 22 30 40](https://cloud.githubusercontent.com/assets/9413437/6156922/adbb16b4-b23d-11e4-829e-f634d5cb1851.png)
![schermata 2015-02-11 alle 22 30 46](https://cloud.githubusercontent.com/assets/9413437/6156923/adc3d6f0-b23d-11e4-9a8d-6752613c4d7f.png)

**Comment by klleshi** [comment]
Con FireFox e Chrome funziona bene

Il 11/02/2015 22:35, 842647 ha scritto:

**Comment by 842647** [comment]
Con safari no :-1: vedo di capire cosa fare.. :cry:

**Comment by fundor333** [comment]
Il footer con copyright evidenziato lo ho sistemato, come ho sistemato il testo alternativo
