### ISSUE TITLE
[FOTOGALLERY] 0 results

### ISSUE THREAD

**Issue by alex-danieli** [InformaticaSaraLei/ProgettoSito#90]
Ciao,
ho notato uno strano "0 results" dopo lo slideshow in fondo del content della pagina.

**Comment by simonix93** [comment]
Ciao,
io non vedo nulla!

**Comment by MargheritaRossi** [comment]
nemmeno io! vuoi/puoi postarci una screenshot?

**Comment by simonix93** [comment]
piuttosto ho notato che nella pagina della fotogallery il footer è diverso dalle altre pagine ( non occupa tutto lo schermo).

**Comment by MargheritaRossi** [comment]
controllo subito grazie

**Comment by andreafrison** [comment]
Attenzione alle modifiche nelle pagine! Se i div non sono chiuesi correttamente il footer subisce..

**Comment by simonix93** [comment]
Mi sembra che tutti i div siano chiusi correttamente. Quindi non credo sia quello il problema.

**Comment by fundor333** [comment]
Il php generava male la chiusura dei div per cui non veniva visualizzato il footer. Ora è stato corretto

**Comment by simonix93** [comment]
dopo i tuoi aggiornamenti c'è però ora un problema di visualizzazione delle foto. Nella prima riga lascia due spazi vuoti.

**Comment by simonix93** [comment]
dovremmo aver risolto
