### ISSUE TITLE
parte amministrativa: ultime cose

### ISSUE THREAD

**Issue by Tpierluigi** [InformaticaSaraLei/ProgettoSito#93]
Ciao,

ultime due cose per chiedere definitivamente la parte amministrativa:

@InformaticaSaraLei/integrazioneecontrollo : ho aggiunto la breadcrumb sulla dashboard e pagine correlate, quando la VPN con ca'Foscari tornerà in piedi, bisognerà allineare test01 (cartella admin/)

@lzuffellato @mrscarpa93 manca una sezione dedicata a gestire l'elenco di destinatari(e) della newsletter; sulla cartella /servizi ci sono i files per gestire la newsletter, manca l'interfaccia utente.

Pierluigi [Integrazione & controllo]

**Comment by emanuela83** [comment]
Ciao

test01 e riallineato secondo gli aggiornamenti di github (fatto da laboratorio unive).
Sembra che VPN ritornerà a funzionare da domani.

Un saluto [Integrazione e Controllo]

**Comment by emanuela83** [comment]
ci sono ancora problemi  di visualizzazione del footer tra un browser al altro. 
ho provato con explorer 11:
![footer](https://cloud.githubusercontent.com/assets/9656089/6236783/c7956da0-b6ed-11e4-9ba0-17b3dc68bfd9.png)

invece con crome:
![footer1](https://cloud.githubusercontent.com/assets/9656089/6236795/e44cc542-b6ed-11e4-9c65-007a64a7c19b.png)

**Comment by fundor333** [comment]
Abbiamo testato il problema sui browser indicati ma non si sono presentati i problemi mostrati. Se riesci a mandarmi il terminale del browser riusciamo a vedere se è un problema temporaneo o no.

**Comment by fundor333** [comment]
Abbiamo riscontrato che i link social scompaiono con AdBlock attivo. Per l'altro problema l'abbiamo trovato: è un cattivo rendering di IE

**Comment by fundor333** [comment]
Ho pushato la correzione degli errori. Ora dovrebbe funzionare

**Comment by emanuela83** [comment]
@fundor333 si funziona . grazie
