### ISSUE TITLE
Bando Regione Veneto

### ISSUE THREAD

**Issue by TBuc** [InformaticaSaraLei/ProgettoSito#96]
Propongo di inserire il seguente contenuto (tra le opportunità??):

"Aiuti agli investimenti delle nuove PMI a prevalente partecipazione femminile". Programma Operativo Regionale 2007-2013.
http://www.regione.veneto.it/web/bandi-avvisi-concorsi/dettaglio-bando?_spp_detailId=415613

**Comment by TBuc** [comment]
P.S.: so che è scaduto, ma non ho trovato proroghe nè nuovi bandi in merito.
Valutate voi se è comunque di interesse o meno (o magari se qualcuno trovasse un bando simile ma ancora in essere sarebbe il top).

**Comment by NicolaFrx** [comment]
Le opportunità culturali sono state trasformate in 'Testimonianze' perciò al massimo può essere aggiunto al calendario nelle vecchie date.
Grazie comunque, hai aperto un po' la strada sul contenuto da offrire negli eventi!

**Comment by TBuc** [comment]
@NicolaFrx super!

OT: non so perchè, ma via email mi arrivano un sacco di notifiche da GitHub - tranne quelle dei topic che mi interessano.
