### ISSUE TITLE
Parte grafica del sito, ultime cose. 

### ISSUE THREAD

**Issue by klleshi** [InformaticaSaraLei/ProgettoSito#97]
@fundor333 
@andreafrison 
In vista del incontro di Lunedì (che sarà decisivo per il nostro progetto), chiederei gentilmente di dare un controllo alla grafica se è tutto come previsto da voi (i panelli, buttoni, testo  …)

**Comment by NicolaFrx** [comment]
Vorrei segnalare che quando si apre un video nella home, se questo non viene messo in pausa nel momento dell'uscita, la visualizzazione continua in background.

Ispezionando la pagina con vari browser inoltre, vengono presentati vari errori, che siano correlati al problema sopra esposto? Metto uno screen di firefox.
![errori](https://cloud.githubusercontent.com/assets/9415348/6286793/a661e7e2-b90b-11e4-99c0-ec673da78370.png)

IE propone alcuni consigli: https://msdn.microsoft.com/en-us/library/ie/dn887953(v=vs.94).aspx

**Comment by NicolaFrx** [comment]
Si potrebbe rendere responsive anche questo video?

http://test01.dsi.unive.it/erasmus/index.php?page=content/going-abroad/what-do-I-need.php

**Comment by emanuela83** [comment]
volevo segnalare che pagina dei #Link Utili  ogni link esterno deve essere aperto su una nuova scheda
 Grazie [Integrazione e Controllo]

**Comment by fundor333** [comment]
@NicolaFrx Tutti i problemi evidenziati sono dati da css e sono legati ai tag esclusivi dei vari broswer. In oltre il problema sorge dal fatto che tu non cambi pagina chiudendo la finestra del video (chi naviga e guarda i video è sempre nella home).

Per quanto riguarda il video responsive credo di averlo sistemato ma bisogna che diate una occhiata

**Comment by NicolaFrx** [comment]
Il video adesso è responsive (forse un po' troppo grande di default ma credo possa andare), grazie

Mi spiego meglio:
se rimango nella home a guardare i video e
ne guardo uno, poi a metà video clicco close,
e ne apro un altro sempre nella home,
entrambi continuano a processare,
mantenendo attiva la visualizzazione.
La cosa positiva è che più di due non vanno, potrebbe comunque essere considerata una piccolezza ;)

Grazie per il chiarimento sugli errori

**Comment by fundor333** [comment]
Quello bisogna mettere mano al js che gestisce l effetto nuova pagina. Ho
provato a sistemarlo ma non ho avuto risultato soddisfacente

MS

**Comment by NicolaFrx** [comment]
ok nessun problema, per il resto possiamo chiudere l'issue?

**Comment by andreafrison** [comment]
Mi sembra risolto il problema del "close&stop" no?

**Comment by NicolaFrx** [comment]
A dire il vero no,
sono riuscito ad aprire tutti i video disponibili e a riprodurli contemporaneamente sulla stessa pagina..

**Comment by andreafrison** [comment]
Abbiamo visto che con firefox il video si ferma correttamente. Stiamo cercando una soluzione per gli altri browser

**Comment by TBuc** [comment]
Confermo che su Firefox funziona, e che su Chrome dà il noto problema.
Ma ho appena provato su IE 11 e non carica neppure il video! È perchè state facendo dei test?

**Comment by andreafrison** [comment]
Il codice non l'abbiamo ancora toccato. Sto facendo delle prove da un'altra parte.

**Comment by andreafrison** [comment]
@NicolaFrx @TBuc 
Ho appena fatto un commit con le modifiche.. ora sul mio mac su firefox, chrome e safari alla chiusura ferma il video.

**Comment by TBuc** [comment]
@andreafrison hai uppato le modifiche sul server test01?
Perchè ho appena provato ma con Chrome e con IE continua a dare lo stesso problema (ora si comporta allo stesso modo su entrambi).

**Comment by fundor333** [comment]
@TBuc Noi non abbiamo i diritti di Upload

**Comment by TBuc** [comment]
@fundor333 OK allora se vi serve qualche beta tester fate un fischio non appena vi siete fatti uploadare l'ultima versione.

@andreafrison i video dal numero 7 in poi non vengono caricati: è cosa nota?

**Comment by andreafrison** [comment]
Non ci sono ancora stati forniti..
Il 22/feb/2015 13:42 "Antonio Bucciol" <notifications@github.com> ha
scritto:

**Comment by NicolaFrx** [comment]
Ottimo lavoro, scusate per la rottura!

**Comment by andreafrison** [comment]
Figurati! Se ci sono altri problemi facci sapere
Il 22/feb/2015 13:54 "Nicola Baldo" <notifications@github.com> ha scritto:

**Comment by NicolaFrx** [comment]
Ok, un'ultima cosa allora,
nel footer i link interni al dominio (utili e about) vengono comunque aperti su nuova scheda,
è fatto apposta?

**Comment by andreafrison** [comment]
Non credo proprio. Probabilmente é stata fatta una sostituzione di massa..
Il 22/feb/2015 14:07 "Nicola Baldo" <notifications@github.com> ha scritto:

**Comment by NicolaFrx** [comment]
Ok grazie, per internet explorer si riescono a sistemare i video?

**Comment by klleshi** [comment]
A tuti i team
Server test01 è allineato con gitHub. In caso di ulteriori commit, per favore avvisateci.
