### ISSUE TITLE
VPN ATENEO

### ISSUE THREAD

**Issue by TBuc** [InformaticaSaraLei/ProgettoSito#98]
@klleshi @Tpierluigi 
Ho problemi con la VPN d'Ateneo: sono riuscito ad apportare una sola modifica sul server.

Tutte le altre variazioni vanno eseguite. Le ho elencate in un file, `database_src/TO BE EXECUTED.sql`.

Il primo che riesce a connettersi alla VPN e a eseguirle rimuova il file :) Io riproverò domani pomeriggio.

**Comment by klleshi** [comment]
@TBuc 
Ho eseguito le query e rimosso il file come avevi richiesto.
