### ISSUE TITLE
Ultimo commit

### ISSUE THREAD

**Issue by alex-danieli** [InformaticaSaraLei/ProgettoSito#99]
Ciao,
mi stavo chiedendo quale è l'ultimo commit previsto prima della presentazione ...
Se avessi bisogno di fare in extremis un commit su test01 chi mi può assistere?

Grazie
Alex D.

**Comment by klleshi** [comment]
La presentazione è fissata per domani, sarebbe corretto che stasera 
(anche tardi) fosse l'ultimo commit. Quindi siamo a disposizione.

Il 22/02/2015 11:19, alex-danieli ha scritto:

**Comment by alex-danieli** [comment]
Grazie 1000 ... mi son accorto di alcune piccole modifiche non bloccanti e volevo capire se per domani potessero essere visibili.

Grazie
AleXD

**Comment by alex-danieli** [comment]
Io ho chiuso i piccoli interventi "non bloccanti" ... attendo aggiornamento di test01, se non avvenisse, nessun problema è comunque presentabile :D

**Comment by klleshi** [comment]
@alex-danieli 
Server test01 è stato aggiornato, quindi puoi verificare le tue modifiche.
